server:
  port: 9000
  servlet:
    encoding:
      charset: UTF-8
      enabled: true
      force: true

spring:
  application:
    name: nagnae

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: ${MYSQL_URL:jdbc:mysql://localhost:3306/nagnae_db?serverTimezone=UTC&useUniCode=yes&characterEncoding=UTF-8}
    username: ${MYSQL_USERNAME:nagnae}
    password: ${MYSQL_PASSWORD:nagnae!}


  servlet:
    multipart:
      enabled: true
      max-file-size: 50MB
      max-request-size: 50MB

mybatis:
  type-aliases-package: com.learningman.nagnae.domain.dto, com.learningman.nagnae.authorization.dto, com.learningman.nagnae.authorization.model
  configuration:
    map-underscore-to-camel-case: true
  mapper-locations: classpath:mapper/*.xml

file:
  upload:
    windows: C:\Users\hi02\dev\upload\
    linux: /app/upload/

logging:
  level:
    com.learningman.nagnae.authorization.repository.UserRepository: TRACE
    com.learningman.nagnae.board.repository.BoardMapper: TRACE
    com.learningman.nagnae.chatbot.repository.ChatHistoryRepository: TRACE
    com.learningman.nagnae.study.repository.StudyMapper: TRACE


