server:
  port: 9000
  servlet:
    encoding:
      charset: UTF-8
      enabled: true
      force: true

spring:
  application:
    name: nagnae

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: ${MYSQL_URL:jdbc:mysql://nagnae-1.c1waa6wu6dvf.ap-northeast-2.rds.amazonaws.com:3306/nagnae_db?serverTimezone=UTC&useUniCode=yes&characterEncoding=UTF-8}
    username: ${MYSQL_USERNAME:admin}
    password: ${MYSQL_PASSWORD:nagnae12!}


  servlet:
    multipart:
      enabled: true
      max-file-size: 50MB
      max-request-size: 50MB
      

  mail:
    host: smtp.gmail.com
    port: 587
    username: lukdown10@gmail.com
    password: huaf ebds phqp xhbv
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

#  mvc:
#    cors:
#      allowed-origins: http://localhost:3000, http://localhost:8000, http://nagnae.site
#      allowed-methods: GET,POST,PUT,DELETE,OPTIONS
#      allowed-headers: "*"
#      allow-credentials: true

mybatis:
  type-aliases-package: com.learningman.nagnae.domain.dto, com.learningman.nagnae.authorization.dto, com.learningman.nagnae.authorization.model
  configuration:
    map-underscore-to-camel-case: true
  mapper-locations: classpath:mapper/*.xml

file:
  upload:
    windows: C:\Users\hi02\dev\upload\
    linux: /app/upload/

logging:
  level:
    com.learningman.nagnae.authorization.repository.UserRepository: TRACE
    com.learningman.nagnae.board.repository.BoardMapper: TRACE
    com.learningman.nagnae.chatbot.repository.ChatHistoryRepository: TRACE
    com.learningman.nagnae.study.repository.StudyMapper: TRACE
