name: Deploy nagnae App

# 수동으로 푸시할려면 주석풀고 깃허브에 올려서 깃허브에서 올리세요
#on:
#  workflow_dispatch:
#    inputs:

on:
  push:
    branches:
      - master # 또는 프로젝트의 기본 브랜치명

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up JDK 17
      uses: actions/setup-java@v2
      with:
        java-version: '17'
        distribution: 'temurin'

    - name: Setup Gradle
      uses: gradle/gradle-build-action@v2

    - name: Grant execute permission for gradlew
      run: chmod +x gradlew

    - name: Build with Gradle
      run: ./gradlew clean build

    - name: Build Docker image
      run: docker build . -t hyunsujung3679/nagnae-spring-20240823-1:latest

    - name: Log in to Docker Hub
      run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

    - name: Push Docker image to Docker Hub
      run: docker push hyunsujung3679/nagnae-spring-20240823-1:latest

  SSH:
    needs: build-and-deploy
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: SSH to EC2
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.EC2_HOST }}
        username: ${{ secrets.EC2_USERNAME }}
        key: ${{ secrets.SSH_PRIVATE_KEY }}
        script: |
          sudo mkdir -p /home/ubuntu/upload
          sudo docker pull hyunsujung3679/nagnae-spring-20240823-1:latest
          sudo docker stop nagnae-spring-20240823-1 || true
          sudo docker rm nagnae-spring-20240823-1 || true
          sudo docker run -d \
            --name nagnae-spring-20240823-1 \
            -p 9000:9000 \
            -v /home/ubuntu/upload:/app/upload \
            -e MYSQL_URL="jdbc:mysql://nagnae-1.c1waa6wu6dvf.ap-northeast-2.rds.amazonaws.com:3306/nagnae_db?serverTimezone=UTC&useUniCode=yes&characterEncoding=UTF-8" \
            -e MYSQL_USERNAME="admin" \
            -e MYSQL_PASSWORD="nagnae12!" \
            hyunsujung3679/nagnae-spring-20240823-1:latest
